// Auto-generated by update_campaign_data.ps1 on 2026-04-16 14:01:20
// Source: nurturing_metadata_synchronous_json.cc
// Total campaigns: 236
// DO NOT EDIT MANUALLY - run update_campaign_data.ps1 to regenerate

const campaignData = {
    "M365OpenLinks": {
        name: "M365 Open Links",
        subcategories: {
            "inform_banner": {
                name: "Inform Banner",
                campaigns: [
                            "M365OpenLinks_InformBannerVariant1",
                            "M365OpenLinks_InformBannerVariant2",
                            "M365OpenLinks_InformBannerVariant3",
                            "M365OpenLinks_InformBannerVariant4"
                ]
            }
,
            "inform_flyout": {
                name: "Inform Flyout",
                campaigns: [
                            "M365OpenLinks_InformVariant1",
                            "M365OpenLinks_InformVariant2",
                            "M365OpenLinks_InformVariant3",
                            "M365OpenLinks_InformVariant4"
                ]
            }
,
            "managed": {
                name: "Managed Banners",
                campaigns: [
                            "M365OpenLinks_ManagedBanner"
                ]
            }
,
            "optout_banner": {
                name: "OptOut Banner",
                campaigns: [
                            "M365OpenLinks_OptOutBannerVariant1",
                            "M365OpenLinks_OptOutBannerVariant2",
                            "M365OpenLinks_OptOutBannerVariant3",
                            "M365OpenLinks_OptOutBannerVariant4"
                ]
            }
,
            "optout_flyout": {
                name: "OptOut Flyout",
                campaigns: [
                            "M365OpenLinks_OptOutVariant1",
                            "M365OpenLinks_OptOutVariant2",
                            "M365OpenLinks_OptOutVariant3",
                            "M365OpenLinks_OptOutVariant4",
                            "M365OpenLinks_OptOutLastFlyOutBingVariant"
                ]
            }
,
            "optout_modal": {
                name: "OptOut Modal",
                campaigns: [
                            "M365OpenLinks_OptOutModalVariant1",
                            "M365OpenLinks_OptOutModalVariant2",
                            "M365OpenLinks_OptOutModalVariant4"
                ]
            }
,
            "optout_sidebar": {
                name: "OptOut Sidebar",
                campaigns: [
                            "M365OpenLinks_OptOutSidebarAlwaysShow",
                            "M365OpenLinks_OptOutSidebarAutoHide",
                            "M365OpenLinks_OptOutSidebarAlwaysShowLast",
                            "M365OpenLinks_OptOutSidebarAutoHideLast"
                ]
            }
,
            "other": {
                name: "Other",
                campaigns: [
                            "M365OpenLinks_TeamsManagedBanner"
                ]
            }
,
            "teams_inform": {
                name: "Teams Inform",
                campaigns: [
                            "M365OpenLinks_TeamsInformPrompt",
                            "M365OpenLinks_TeamsInformBanner"
                ]
            }
,
            "teams_optout": {
                name: "Teams OptOut Flyout",
                campaigns: [
                            "M365OpenLinks_TeamsOptOutVariant1",
                            "M365OpenLinks_TeamsOptOutVariant2",
                            "M365OpenLinks_TeamsOptOutVariant3"
                ]
            }
,
            "teams_optout_banner": {
                name: "Teams OptOut Banner",
                campaigns: [
                            "M365OpenLinks_TeamsOptOutBannerVariant1",
                            "M365OpenLinks_TeamsOptOutBannerVariant2"
                ]
            }
        }
    }
,
    "OnRamp": {
        name: "OnRamp",
        subcategories: {
            "advance_ci": {
                name: "Advance CI",
                campaigns: [
                            "OnRamp_AdvanceCIConsent",
                            "OnRamp_AdvanceCIConsentAndAutolaunch",
                            "OnRamp_AdvanceCIConsentConversionAndThemes"
                ]
            }
,
            "autolaunch": {
                name: "Auto Launch",
                campaigns: [
                            "OnRamp_AutolaunchForEEA",
                            "OnRamp_Autolaunch",
                            "OnRamp_AutolaunchAndOpenTabsIfChromePreInstalled",
                            "OnRamp_AutolaunchOnLaunchOptInVariant",
                            "OnRamp_AutolaunchOnLaunchOptOutVariant"
                ]
            }
,
            "continuous_import": {
                name: "Continuous Import",
                campaigns: [
                            "OnRamp_CIExplicitLaunchBannerUpsell",
                            "OnRamp_CIOpenTabs",
                            "OnRamp_CIAutoLaunchDogFoodCampaign",
                            "OnRamp_CIAllDataTypesEnabled",
                            "OnRamp_CIUpsell_ProtocolLaunch_Banner"
                ]
            }
,
            "experiments": {
                name: "Experiments",
                campaigns: [
                            "OnRamp_NurturingViaProng_Experiment",
                            "OnRamp_DriveTravelUsageViaProng_Experiment"
                ]
            }
,
            "other": {
                name: "Other",
                campaigns: [
                            "OnRamp_MaiThemeMigrationNotificationFlyout",
                            "OnRamp_ThemesMigrationBanner",
                            "OnRamp_FastFollowSCFREAfterNDFRE"
                ]
            }
,
            "retrigger_fre": {
                name: "Retrigger FRE",
                campaigns: [
                            "OnRamp_ReTriggerOnWinUpgrade",
                            "OnRamp_RetriggerFREOnEdgeVersionUpgradeViaExplicitLaunch",
                            "OnRamp_RetriggerFRECodexCoPilotExplicitAprd",
                            "OnRamp_RetriggerFRECodexCoPilotAutoAprd",
                            "OnRamp_RetriggerFREOnEdgeVersionUpgradeViaProtocolLaunch",
                            "OnRamp_RetriggerFREOnWinUpgradeViaProtocolLaunch",
                            "OnRamp_RetriggerFREOnExplicitProtocolPDFLaunchForEdgePostDMA",
                            "OnRamp_RetriggerFREForODDReconsentForEdgePostDMA",
                            "OnRamp_RetriggerFREForSkippedFREUsers",
                            "OnRamp_RetriggerFREOnAutolaunchPostSCOOBE",
                            "OnRamp_RetriggerFREForGPTCampaign"
                ]
            }
        }
    }
,
    "FunctionalNotifications": {
        name: "Functional Notifications",
        campaigns: [
            "FN_AIThemeUserConsentDialog",
            "FN_EdgeMitigateSuspiciousDSE",
            "FN_EdgeReclaimDB",
            "FN_IgnoreCawView",
            "FN_IgnoreCawView2",
            "FN_IncognitoWindowCountView",
            "FN_WebToBrowserPostSigninView",
            "FN_WebToBrowserSigninConsentView",
            "FN_IncognitoMenuView",
            "FN_ProfileCustomizationView",
            "FN_DiceWebSignInInterceptionView",
            "FN_ProfileChooserView",
            "FN_PasswordAccountChooserDialog",
            "FN_AppBlockDialogView",
            "FN_AppPauseDialogView",
            "FN_ChromeLabsFlyout",
            "FN_GlobalErrorFlyout",
            "FN_FileSystemAccessFlyout",
            "FN_HCWithThemeBubble",
            "FN_ZoomBubbleView",
            "FN_GeoLocationPermissionFlyout",
            "FN_LowDiskSpaceFlyout",
            "FN_InternetExplorerFlyout",
            "FN_IndicatorInfoFlyout",
            "FN_IncognitoClearDataFlyout",
            "FN_HomeButtonFlyout",
            "FN_PriceTrackingBubbleCoordinator",
            "FN_DesktopMediaPickerDialogView",
            "FN_DownloadToolbarButtonView",
            "FN_AdAndTrackerInfoBubbleView",
            "FN_CollaboratorHoverCard",
            "FN_ContentSettingImageView",
            "FN_EdgeIntentPickerBubbleView",
            "FN_ChipController",
            "FN_FlyingIndicatorBubbleView",
            "FN_Modal_EdgeCustomizedHRDView",
            "FN_EdgeWebshotBubbleView",
            "FN_EdgeEasyAuthSignInPromptView",
            "FN_EdgeSuperResolutionPopup",
            "FN_Modal_EdgeOneAuthSigninView",
            "FN_Modal_ExtensionInstalledDialog",
            "FN_Modal_ExtensionPopup",
            "FN_ReadAloudSettingsBubbleView",
            "FN_Modal_EdgePermission",
            "FN_PageInfoPopup",
            "FN_BookmarkBubleView",
            "FN_SendTabToSelfPromoView",
            "FN_SendTabToSelfMobileUpsell",
            "FN_SendTabToSelfToolbarBubble",
            "FN_SetAsideSnoozeBubbleView",
            "FN_TabGroupHelperView",
            "FN_TabGroupAutogroupingBubbleView",
            "FN_Identity_SignInReauthCTA",
            "FN_EdgeTranslateBubbleView",
            "FN_PrismExplorerBubble",
            "FN_PasswordBubbleView",
            "FN_CaptionBubble",
            "FN_EdgePwaConfirmationFlyout",
            "FN_WebAppPostInstallView",
            "FN_WebAppInstallPromptNotification",
            "FN_BrowserExperiences_VerticalTabsFeedback",
            "FN_TryProfileSwitcherView",
            "FN_M365LinksOptOutAdjustSettingView",
            "FN_RelaunchRecommendedBubble",
            "FN_AccountSelectionView",
            "FN_ThrobberBubble",
            "FN_CustomPasswordAuthDialog",
            "FN_TabHoverCardBubble",
            "FN_EmojiFlyout",
            "FN_MiniCardBubbleView",
            "FN_BNPLVirtualCardFlyout",
            "FN_VirtualCardFlyout",
            "FN_RoamingCardTokenizationFailureFlyout",
            "FN_HistoryHoverCardView",
            "FN_SmartSwitchBubbleView",
            "FN_EdgeFundamentals_AlwaysUpToDate",
            "FN_SplitScreenPermissionFlyout",
            "FN_Overflow_Menu",
            "FN_ShorelineHoverCard",
            "FN_MediaFlyout",
            "FN_StoragePressureFlyout",
            "FN_DLP_Dialog",
            "FN_ToastDialogFlyout",
            "FN_ToolbarHoverFlyout",
            "FN_WdagFlyout",
            "FN_XboxGameModeFlyout",
            "FN_ManagedSiteFlyout",
            "FN_QRGeneratorFlyout",
            "FN_CriticalNotificationFlyout",
            "FN_BatterySaverFlyout",
            "FN_HighEfficiencyFlyout",
            "FN_CompoundResigninSaveCardFlyout",
            "FN_AutoSigninFirstRunDialogView",
            "FN_EdgeWorkSearchResultsBannerOnBingSERP",
            "FN_BrowserHassles",
            "FN_ProtectedDownloadsSaveAsDialog",
            "FN_ThemeAppliedUndoInfobar",
            "FN_FrequentSitesConsentBanner",
            "FN_browser-action-message-done"
        ]
    }
,
    "FN_OnRamp": {
        name: "FN OnRamp",
        campaigns: [
            "FN_OnRamp_AutolaunchOnWindowsUnlock",
            "FN_OnRamp_PersonalizedLaunch_OptOut_Variant",
            "FN_OnRamp_PersonalizedLaunch_V3_Retrigger"
        ]
    }
,
    "FN_Password": {
        name: "FN Password & Security",
        campaigns: [
            "FN_Password_BreachInContextAlert",
            "FN_Password_BreachInContextAlert2",
            "FN_Password_CopilotAssistedPasswordChangeAlert",
            "FN_Password_BreachConsentDialog"
        ]
    }
,
    "FN_VideoTranslate": {
        name: "FN Video Translation",
        campaigns: [
            "FN_VideoTranslate_ParametersSelection_Flyout",
            "FN_VideoTranslate_Installation_Flyout",
            "FN_VideoTranslate_Preparation_Flyout",
            "FN_VideoTranslate_Error_Flyouts"
        ]
    }
,
    "FN_Workspace": {
        name: "FN Workspace",
        campaigns: [
            "FN_EdgeWorkspaceBubbleView",
            "FN_EdgeWorkspaceInviteBubbleView",
            "FN_EdgeWorkspaceErrorModal",
            "FN_EdgeSpaceworkPopup"
        ]
    }
,
    "FN_Extensions": {
        name: "FN Extensions",
        campaigns: [
            "FN_ExtWebstoreModal",
            "FN_UserSettingsExtensionDisabledBubbleView",
            "FN_ExtOtherStoreInstallModal",
            "FN_ExtInstallFrictionModal",
            "FN_ExtensionMigrationFlyout",
            "FN_ExtensionMenuView",
            "FN_ExtensionWidget",
            "FN_ExtensionInstallDialog",
            "FN_ExtFriction_Dialog"
        ]
    }
,
    "Shopping": {
        name: "Shopping",
        subcategories: {
            "bing_integration": {
                name: "Bing Integration",
                campaigns: [
                            "SHOPPING_AUTO_SHOW_BING_SEARCH",
                            "SHOPPING_AUTO_SHOW_BING_CAMPAIGN"
                ]
            }
,
            "cashback_rebates": {
                name: "Cashback & Rebates",
                campaigns: [
                            "Shopping_EnableShoppingAssistance_Cashback_Success_Banner",
                            "SHOPPING_AUTO_SHOW_REBATES_CONFIRMATION",
                            "SHOPPING_AUTO_SHOW_REBATES_DEACTIVATED",
                            "SHOPPING_AUTO_SHOW_REBATES_BING",
                            "SHOPPING_AUTO_SHOW_PERSONALIZED_CASHBACK",
                            "SHOPPING_AUTO_SHOW_PERSONALIZED_CASHBACK_CONFIRMATION",
                            "SHOPPING_AUTO_SHOW_URL_PARAM_REBATES",
                            "SHOPPING_AUTO_SHOW_REBATES_ACTIVATION_FAILED",
                            "SHOPPING_AUTO_SHOW_REBATES_SWITCHED_TO_MSA",
                            "SHOPPING_AUTO_SHOW_ENROLL_TO_CASHBACK_CONFIRMATION_NOTIFICATION"
                ]
            }
,
            "other": {
                name: "Other",
                campaigns: [
                            "SHOPPING_AUTO_SHOW_ITEM_ADDED_TO_CART_FROM_OTHER_SELLER",
                            "SHOPPING_OPEN_FLYOUT_FROM_EDGE_DRIVER",
                            "SHOPPING_AUTO_SHOW_SUSTAINABILITY_PURCHASE",
                            "SHOPPING_AUTO_SHOW_REWARDS_ACTIVATION_FAILED",
                            "SHOPPING_AUTO_SHOW_REWARDS_SWITCHED_TO_MSA",
                            "SHOPPING_AUTO_SHOW_SHOPRUNNER_CONFIRMATION"
                ]
            }
,
            "price_tracking": {
                name: "Price Tracking",
                campaigns: [
                            "SHOPPING_AUTO_SHOW_URL_PARAM_PRICE_COMPARISON",
                            "SHOPPING_AUTO_SHOW_URL_PARAM_PRICE_HISTORY"
                ]
            }
,
            "virtual_cards": {
                name: "Virtual Cards",
                campaigns: [
                            "SHOPPING_AUTO_SHOW_VIRTUAL_CARD"
                ]
            }
        }
    }
,
    "Bing": {
        name: "Bing",
        campaigns: [
            "Bing_RecommendedSettingsExplicitLaunch",
            "Bing_DefaultBrowserBannerCloseBtn",
            "Bing_RecommendedSettingsExpandedTriggeringDialog",
            "Bing_Instrumentation"
        ]
    }
,
    "BingChina": {
        name: "Bing China",
        campaigns: [
            "BingChina_BannerDefaultBrowser",
            "BingChina_UpsellDefaultSettingsFlyout"
        ]
    }
,
    "RecommendedSettings": {
        name: "Recommended Settings",
        campaigns: [
            "RecommendedSettingsChina"
        ]
    }
,
    "EdgeMobile": {
        name: "Edge Mobile",
        campaigns: [
            "EdgeMobile_MobileUpsell_Email_AF_AnimationExtensionInstall",
            "EdgeMobile_MobileUpsell_Email_AF_AnimationExtensionInstallCN",
            "EdgeMobile_MobileUpsell_Email_AF_Animation_Pwd_Autofill",
            "EdgeMobile_MobileUpsell_Rewards_Referral",
            "EdgeMobile_MobileUpsell_Rewards_1M_Lottery"
        ]
    }
,
    "EdgeOnMac": {
        name: "Edge on Mac",
        campaigns: [
            "EdgeOnMac_SetEdgeAsDefaultBrowserOnMac",
            "EdgeOnMac_OneTimeManualImportStatusSuccess",
            "EdgeOnMac_OneTimeManualImportStatusFailure",
            "EdgeOnMac_SafariPasswordImportFailure",
            "EdgeOnMac_CopilotModeCampaignOnMac"
        ]
    }
,
    "EnterpriseSecurity": {
        name: "Enterprise Security",
        campaigns: [
            "EnterpriseSecurity_MitigationBanner",
            "EnterpriseSecurity_CmdLineBadUrlMitigationBanner"
        ]
    }
,
    "DualEngine": {
        name: "Dual Engine",
        campaigns: [
            "DualEngine_PinEdge"
        ]
    }
,
    "Fundamentals": {
        name: "Fundamentals",
        campaigns: [
            "Fundamentals_InterceptSuspFavorite",
            "Fundamentals_FN_ReclaimDBForEdgeProtocol"
        ]
    }
,
    "Sync": {
        name: "Sync Growth & Activation",
        campaigns: [
            "SyncGrowthAndActivation_AccountLevelSyncConsentSyncOff",
            "SyncGrowthAndActivation_AccountLevelSyncConsentSyncOn"
        ]
    }
,
    "EdgePreview": {
        name: "Edge Preview",
        campaigns: [
            "EdgePreview_EnrollmentNotification"
        ]
    }
,
    "NTP": {
        name: "New Tab Page",
        campaigns: [
            "NTP_UpsellCampaign",
            "NTP_SettingsCampaign",
            "NTP_FunctionalCampaign"
        ]
    }
,
    "Toolbar": {
        name: "Toolbar",
        campaigns: [
            "Toolbar_PersonalizationFlyout"
        ]
    }
,
    "Identity": {
        name: "Identity",
        campaigns: [
            "Identity_AccountTransfer"
        ]
    }
};
